### ISSUE TITLE
Can you please clarify this?

### ISSUE THREAD

**Issue by sdeering** [aloha/laravel-twilio#78]
"Define multiple entries in your twilio config to make use of this feature."

```
'from' => '+447903568xxx',
```

-------------------------------------------------

Facade

The facade now has the exact same methods as the Aloha\Twilio\TwilioInterface. One extra feature is that you can define which settings (and which sender phone number) to use:

Twilio::from('callcenter')->message($user->phone, $message);
Twilio::from('board_room')->message($boss->phone, 'Hi there boss!');
Define multiple entries in your twilio config to make use of this feature.

**Comment by hannesvdvreken** [comment]
It depends. What version do you have installed?
This documentation is for the 2.0.0-alphaX versions.

**Comment by hannesvdvreken** [comment]
Oh, I think I see what you want to know:

"multiple entries" refers to the "twilio.connections" configuration array.
Add more keyed configuration objects in there, in order to use the `$twilio->from($key)->...` functionality.

If you think it is not clear, you can always adjust the documentation so others will have an easier job of figuring out how this works. Help would be highly appreciated!

**Comment by hannesvdvreken** [comment]
fyi: there's a gitter chat room as well now https://gitter.im/aloha/laravel-twilio

**Comment by sdeering** [comment]
Ok cool thanks mate, i'll take a look at the chat.

It's much clearer now that the connections is an array and can specify more than one. Nice.

I am trying to find out how to get a NAME instead of my Twilio number to show in SMS. Any ideas?

fyi - I'm using "aloha/twilio" : "2.0.0-RC2".
